sudo: required

addons:
  apt:
    packages:
      - cmake
      - libsfml-dev
      - gcc

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - cmake ${TRAVIS_BUILD_DIR} && make
  - ./testfb
